junit_tests(
    sources = ["*.scala"],
    compiler_option_sets = ["fatal_warnings"],
    dependencies = [
        "3rdparty/jvm:junit",
        "3rdparty/jvm:mockito-core",
        "3rdparty/jvm:scalatest",
        "3rdparty/jvm:scalatestplus",
        "config",
    ],
)
