scala_library(
    sources = ["*.scala"],
    compiler_option_sets = ["fatal_warnings"],
    dependencies = [
        "3rdparty/jvm:mustache",
        "config",
        "generator/src/main/resources",
    ],
)
