target(
    dependencies = [
        "config/src/main/scala/com/twitter/emoji/config",
    ],
)

target(
    name = "tests",
    dependencies = [
        "config/src/test/scala/com/twitter/emoji/config",
    ],
)
